// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU02TBSmLONsdOVOXaVLnJVW1Sig2NyH4',
    appId: '1:625906855642:web:eab9646478c4852c59ffe3',
    messagingSenderId: '625906855642',
    projectId: 'pocket-khoroch-8b249',
    authDomain: 'pocket-khoroch-8b249.firebaseapp.com',
    storageBucket: 'pocket-khoroch-8b249.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXgbNAXw_CgqFxXZ2QauyRkQQ3Vtyh1Kw',
    appId: '1:625906855642:android:1e3f49c8d42f7ffc59ffe3',
    messagingSenderId: '625906855642',
    projectId: 'pocket-khoroch-8b249',
    storageBucket: 'pocket-khoroch-8b249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ruXdEBa0fNWasJ6erIH-rWBKzi56z94',
    appId: '1:625906855642:ios:ea52bb95470f04ac59ffe3',
    messagingSenderId: '625906855642',
    projectId: 'pocket-khoroch-8b249',
    storageBucket: 'pocket-khoroch-8b249.firebasestorage.app',
    iosClientId: '625906855642-sc0c1pupd3hvir15acmt6jb6evmk1hi0.apps.googleusercontent.com',
    iosBundleId: 'com.yourname.pocketkhoroch.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ruXdEBa0fNWasJ6erIH-rWBKzi56z94',
    appId: '1:625906855642:ios:ea52bb95470f04ac59ffe3',
    messagingSenderId: '625906855642',
    projectId: 'pocket-khoroch-8b249',
    storageBucket: 'pocket-khoroch-8b249.firebasestorage.app',
    iosClientId: '625906855642-sc0c1pupd3hvir15acmt6jb6evmk1hi0.apps.googleusercontent.com',
    iosBundleId: 'com.yourname.pocketkhoroch.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU02TBSmLONsdOVOXaVLnJVW1Sig2NyH4',
    appId: '1:625906855642:web:3ace285f101111ea59ffe3',
    messagingSenderId: '625906855642',
    projectId: 'pocket-khoroch-8b249',
    authDomain: 'pocket-khoroch-8b249.firebaseapp.com',
    storageBucket: 'pocket-khoroch-8b249.firebasestorage.app',
  );
}
